name: dishapp
description: "A recepies social media"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  cached_network_image: ^3.2.1
  cloud_firestore: ^4.17.3
  firebase_auth: ^4.19.3
  firebase_core: ^2.30.1
  firebase_database: ^10.5.5
  flutter:
    sdk: flutter
  flutterflow_ui: ^0.2.0+1
  image_picker: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/images/
  fonts:
    - family: Simple_Lemonade
      fonts:
      - asset: lib/fonts/Simple_Lemonade.otf
    - family: Ginger_Cat
      fonts:
        - asset: lib/fonts/Ginger_Cat.otf
        - asset: lib/fonts/Ginger_Cat.ttf