name: dishapp
description: "A recepies social media"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.0
  responsive_framework: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/images/
  fonts:
    - family: Simple_Lemonade
      fonts:
      - asset: lib/fonts/Simple_Lemonade.otf
    - family: Ginger_Cat
      fonts:
        - asset: lib/fonts/Ginger_Cat.otf
        - asset: lib/fonts/Ginger_Cat.ttf